// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0YoaSFe2c19plUAQK5I5mVM0CCB2TWQ',
    appId: '1:204998889984:web:c8732def55aa91000d7ee5',
    messagingSenderId: '204998889984',
    projectId: 'alpha-capital-super-app',
    authDomain: 'alpha-capital-super-app.firebaseapp.com',
    storageBucket: 'alpha-capital-super-app.appspot.com',
    measurementId: 'G-BH5TFDD81G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIO9zXDh3SQSbD7sZ-4vyd9dUZmnk2Zac',
    appId: '1:204998889984:android:3910b2faebf1d7620d7ee5',
    messagingSenderId: '204998889984',
    projectId: 'alpha-capital-super-app',
    storageBucket: 'alpha-capital-super-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDAO3h-lEmymlcqyj3Uf4T1JN8NNcyxc',
    appId: '1:204998889984:ios:9742c8a24e1332e60d7ee5',
    messagingSenderId: '204998889984',
    projectId: 'alpha-capital-super-app',
    storageBucket: 'alpha-capital-super-app.firebasestorage.app',
    androidClientId: '204998889984-0ro472fmihktjvd4c2ojse7hecu5q3cs.apps.googleusercontent.com',
    iosBundleId: 'com.alphacapital.app',
  );

}