# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
# CocoaPods analytics sends network stats synchronously affecting Flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
# URL format for MintFramework
# This function retrieves the Flutter root directory.
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end


# Loading Flutter's podhelper.rb for additional configuration
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
# Calling the flutter ios pod setup function
flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
pod 'MintFramework', :git => 'https://dharmendraInvestwell@bitbucket.org/mintframeworkios/mintframework.git', :branch => 'master1'
  use_modular_headers!
  # Ensuring Flutter dependencies are installed correctly
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install do |installer|
  # Updating deployment target to iOS 13.0 for all targets
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
	 config.build_settings['SWIFT_VERSION'] = '5.10'  # Specify Swift 5.10 here
         config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
 
      end
    end
  end
  # Adding additional Flutter build settings
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end